
services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://meusql:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - meusql

  meusql:
    image: mysql:8.4
    command: --innodb-use-native-aio=0
    container_name: meusql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    image: dalmeilyri0/nginx-fullcycle:latest
    volumes:
      - ./nignx:/etc/nginx
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
  